### PR TITLE
Drag to resize expando images

### LINKED ISSUE #344: Comments don't fill up entire box
There is a max width of 650px on some internal div in comments that prevents them from filling up the entire shaded comment box. Is this desired?
Demonstration:
Demonstration

### PR DESCRIPTION
**Pull request by quantumwannabe**
Drag to resize images in expandos. Right click on an image to scale it to its native size.

Some notes:
I added an overflow scrollbar to the expandos so that the image can be resized outside of the expandos bounds. RES solves this problem in a different way by making the page wider. If you would prefer RES style large images I can do it, but it requires more calculations and absolute positioning.

The image is now scaled to be 100% of the width of the expando using CSS instead of one-time JS. If the user scales the image and then resizes the window, it is reset to be 100% of the parent's width.

When the expando is hidden, scaled, then shown again the width is reset back to be 100% of the parent's width.

In order to make large images look good in comments, I fixed #344.

Demo:
Demo

### CODE REVIEW

**Comment by DanielFlamino** [comment]
I like seeing the scrollbar more than the way that RES does. In RES the image can "leave" the comment container and looks a bit weird.

**Comment by PuttItOut** [comment]
Looks good.

Questions:
1. Does this work with orientation change on mobile devices? Window resizing? 
2. Do small images get distorted by this code? Will a 65px wide image be stretched 800+px with this logic if viewed on a desktop monitor? Small images shouldn't be stretched by default, shouldn't be stretchable if image fits inside parent container either.

**Comment by quantumwannabe** [comment]
Thanks for the feedback.
It does work with window resizing. I have not tested it on a phone because I could not get remote debugging to see my phone.

You are right, this would distort small images. I'll fix it by using js to add a max-width property to the image.

It does work with comments, I just didn't show it in the demo to keep the gif small.

**Comment by quantumwannabe** [comment]
Ok, images should now no longer be stretched larger than their real size. A max-width property is set to the real width of the image whenever the expando is opened, and it is removed after the user starts to resize it.

**Comment by PuttItOut** [comment]
Quick question Quantum, can we get rid of any of that sizing (width/height) code for images? It looks fairly hacktastic so I was wondering what you thought. Do we still need it?

**Comment by PuttItOut** [comment]
Bonus points: Anyway in the future to allow resizing on all expandos? 

I'm thinking mostly about the HTML5 expandos as I think the .gifv just sizes using 100% width... not sure and too lazy to check ;)

**Comment by quantumwannabe** [comment]
We could probably get rid of a lot of your initial sizing code. I'll take a look and see what I can eliminate. We will still need to get the natural width of the image so that stuff will have to stay (and if the browser doesn't support naturalWidth you only have a hack way to do it).

I believe you can control video width through css. Iframe stuff is non resizable unless everything in the iframe has 100% width. Iframes would also require math to be done to compute the height as they don't have an aspect ratio.

**Comment by PuttItOut** [comment]
Thanks for checking out that sizing code. Every time I scroll past it I cringe a little...

**Comment by quantumwannabe** [comment]
Ok I believe I removed all the code that is no longer needed. If what I deleted was needed for something or it broke something non-obvious or there is more to remove, let me know.

**Comment by voat** [comment]
@PuttItOut - does this PR have your seal of approval for merging? :)

**Comment by PuttItOut** [comment]
Hate to say this since I mentioned it earlier, but I think that sizing code was needed for IE clients...

I can't test this PR right now so I can't say yes or no unfortunately.

**Comment by quantumwannabe** [comment]
The part that had the sizing code with the comment saying IE hack should still work. I am using the older property `width` instead of the more recent `naturalWidth` (IE9+) and taking advantage of the fact that an image not placed into the DOM has its true dimensions as its width and height. I'd be surprised if this doesn't work even in old versions of IE.

**Comment by PuttItOut** [comment]
I just remember having an either or scenario with the width thing. Either is was width or naturalWidth but not both IIRC.

Since apparently no one tests code here (I'm exempt as I have a doctors note), only one way to find out: RELEASE THE CODE.

**Comment by voat** [comment]
Thank you. Looks ok on my end. 

A note for future iteration:
There is no visual cue to show the user that the image can be resized so there is a pretty good chance only people who were active on this PR discussion will use it ;)

**Comment by quantumwannabe** [comment]
Well it is a clone of a RES feature, so anyone who has used it should know how to use it. I agree though that it would be nice to have an icon or something in the lower right corner to indicate resizablity.

**Comment by DanielFlamino** [comment]
What about changing the [cursor CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor)? That should do the trick for desktop users, right?

**Comment by voat** [comment]
nwse-resize should do the trick for a start

**Pull request merged**
