### PR TITLE
Coub embed support

### PR DESCRIPTION
**Pull request by artygus**
Adds support for coub embeds

### CODE REVIEW

**Comment by PuttItOut** [comment]
Thanks for this PR. Just heads up, we have gone all client side on expandos. The server side code should have been deleted.

**Comment by artygus** [comment]
@PuttItOut done!

**Comment by artygus** [comment]
@voat ping

**Comment by igv-on-dev** [comment]
+1

**Comment by over** [comment]
+1

**Comment by DanielFlamino** [comment]
+0

**Comment by voat** [comment]
Thank you for this PR. Could you please target the develop branch as we've changed our workflow. I see no other issues with merging this.Thank you.

**Comment by artygus** [comment]
@voat done https://github.com/voat/voat/pull/816

**Pull request closed without merging**
