### PR TITLE
Minor improvements to user page

### PR DESCRIPTION
**Pull request by gamehelp16**
The user page seems to be a little bit messy for me (imo) and I try to fix it up a little bit, I hope it is good! :)

### CODE REVIEW

**Comment by PuttItOut** [comment]
With UI changes it's really handy for everyone if you'd post before/after screenshots with your PR. Some of us can't easily pull down and test.

**Comment by gamehelp16** [comment]
voatuserprofile

**Comment by gamehelp16** [comment]
Pretty much like that.

**Comment by PuttItOut** [comment]
Hey thanks, looks clean.

**Comment by voat** [comment]
Why did you merge the submission counters with submission distribution? I find this harder to read and I hate when text is directly under a list. If you want to have this merged at all cost, I suggest putting the sentence "This user has so far shared a total of X links" as the first sentence under your "Submission statistics" block instead. Then, follow with "This user has mostly submitted to the followin..." and finally list the distribution "X submissions to X".

As far as the rest goes: why break the consistency with styling? We're using the class "userstats-heading-2" for all level 2 headings, "voting habits" block no longer uses this style. My OCD is alarm is going off when I see different styles on the same page :(

I like the change where you removed the "username wrote:" and replaced it with existing standard formatting.

**Comment by gamehelp16** [comment]
Why did you merge the submission counters with submission distribution? I find this harder to read and I hate when text is directly under a list.

Because imo the submission counters seem to have too little text to "deserve" it's own square, that's just my feeling though.

We're using the class "userstats-heading-2" for all level 2 headings

Does it mean that the class is used sitewide? If yes, sorry for changing the style, I thought it was used on user page only.

"voting habits" block no longer uses this style. My OCD is alarm is going off when I see different styles on the same page :(

I honestly think that the amount of text is too little to "deserve" a heading and using heading will make it feel somewhat cramped.

I like the change where you removed the "username wrote:" and replaced it with existing standard formatting.

Thanks!

**Comment by gamehelp16** [comment]
@PuttItOut Thanks!

**Pull request merged**
