### PR TITLE
Real time preview of markdown text with support for user/subverse/subreddit/url autolinking.

### PR DESCRIPTION
**Pull request by quantumwannabe**
Demo:
Demo

This changes a nuget dependency from MarkdownDeep.NET to MarkdownDeep.Full.

I tried to replace all of the old previews with the new preview, but I wasn't sure where some of them appeared so I couldn't test all of them. It should work for sure on the comment pages (replies and new comments), the subverse settings page, and the compose/reply PM's pages.

Also is there a page full of examples to test the regexes against? I converted the existing C# ones to JS, and tried them against a few examples, but I'm wondering if there already is a test case.

This is a large change so it should probably be closely reviewed before merging.

### CODE REVIEW

**Comment by voat** [comment]
Thank you for this PR. There are several small issues with this which will have to be resolved before merging.

Why are these files changed/added?

Whoaverse/Whoaverse/Graphics/WVSprite.png
Whoaverse/Whoaverse/Graphics/WVSprite.png.css
Whoaverse/Whoaverse/Graphics/WVSprite.png.less
Whoaverse/Whoaverse/Graphics/WVSprite.png.map
Whoaverse/Whoaverse/Graphics/WVSprite.png.scss
Whoaverse/Whoaverse/Scripts/MarkdownDeep License.txt
Whoaverse/Whoaverse/Scripts/MarkdownDeep Quick Reference.txt
Whoaverse/Whoaverse/Scripts/mdd_help.htm
Whoaverse/Whoaverse/Scripts/mdd_styles.css

The realtime preview adds a new toolbar which is redundant since we have our own toolbar to fit voat theme. 

Using MarkdownDeep.Full includes the redundant toolbar and modifies our custom MarkdownDeep binary. Instead of doing so, I suggest only using that which is required by manually adding it to the project and not through Nuget - ie. the MarkdownDeep javascript library.

That would be all I see for now, but if anyone else notices any issues with this, please leave a comment here.

**Comment by PuttItOut** [comment]
I don't know if this is a good idea how this is implemented. We can not have two pipelines for previewing IMO. I think this needs to be discussed as this is a complete duplication of logic.

**Comment by voat** [comment]
Thank you @PuttItOut, I forgot about the additional logic you implemented to linkify things. 

[This is the demo of markdowndeep javascript library with realtime preview](http://www.toptensoftware.com/markdowndeep/dingus). It has full markdown support except for the additional voat linkify logic.

I think we should definitely switch to javascript at some point and ditch the RenderSubmission method in ajaxgatewaycontroller because the task of rendering markdown could be offloaded to clients.

I see no other way to achieve this but to have duplicate logic for voat linkify. Maybe we could simply not linkify in preview mode? Any other thoughts/ideas?

**Comment by PuttItOut** [comment]
I think it should still be server rendered logic. Client side rendering is way to limiting. With server rendering you can check user id's and subverses and not link if they don't exist. You will loose all and any capability of any advanced/intelligent rendering of content if you go client side unfortunately.

Plus with Apps, you might need server side special rendering.

I see nothing but problems with client side in concerns to this.

**Comment by quantumwannabe** [comment]
The main advantage of server side rendering is that you can cache it so it is rendered so each client doesn't have to waste time rendering it. It definitely should not be gotten right of. That said, client side preview can still be useful for previewing content without server round trips. If the logic duplication is my worth it, I still think it is worth it to have a regular markdown preview without any fancy features.

Re:atko
It seems like for forgot to remove some auotmatrically changed files from git before comitting. Looks like nuget added some junk as well. I'll make a new commit to revert them and switch nuguet back to the old thing and add the script file.

Re:puttitout What problems did you see with the logic?

**Comment by voat** [comment]
After a rather long discussion, we've decided not to go with client-side markdown rendering. We will be using server-side parsing which client-side won't be able to utilize and we will need the server-side parsing for third party applications. Fun fact: GitHub is also using server-side processing. If you start writing a comment on GitHub and click the preview tab, you will see that your raw text is sent to GitHub server for rendering, and returned as HTML.

Thank you for working on this, but for now we'll have to stick to the server-side.

**Pull request closed without merging**
