### PR TITLE
Added Mobile Sidebar

### PR DESCRIPTION
**Pull request by quantumwannabe**
Hello,
This PR should add a mobile sidebar per #273. When the breakpoint that the sidebar was previously hidden at (870px) is triggered, a hamburger menu appears in the top left corner. Clicking on it shows and hides the sidebar. Additionally, there is a semi-transparent div behind the sidebar, which if touched/clicked will close the sidebar.

Hopefully this is helpful.

Demonstration:
Gif showing the sidebar being opened

### CODE REVIEW

**Comment by DanielFlamino** [comment]
[Really digging that mobile sidebar, nice job!](https://i.imgur.com/VBTQPrF.gif) :) Funny, I've never heard anyone calling that an hamburger menu, though I can see where the reasoning behind it comes from.

**Comment by voat** [comment]
This looks neat, good job! One minor issue I see with this is that you didn't include voat dark theme support but that could be added later. I'll need some time to test it out before merging and deploying. Thank you for the PR :+1:

**Comment by voat** [comment]
This is now live. The sidebar doesn't work on user profile page (probably a different page layout which is more something we should fix and not you). Thank you for your effort and I'm really looking forward to seeing more PRs from you :)

**Comment by PuttItOut** [comment]
I don't like this and I'm sure others won't either. The sidebar is on the wrong side (UI issue). Dark theme is broken because of this also. All UI changes should be presented on /v/ideasforvoat BEFORE merging without any feedback.

**Comment by voat** [comment]
Can you take a screenshot of the broken dark theme? I couldn't find any issues there. As for the location of the menu - I think it's better than having no sidebar at all. It can be relocated but I also don't see where, the UI is really crammed as it is. Feel free to provide a mockup with a better placement :)

**Comment by quantumwannabe** [comment]
It is a two line css change to make the sidebar on the right side. I chose to put it on the left side because there was no room to put the hamburger icon on the right side and I thought it was a good idea for the icon to be on the same side as the sidebar. Perhaps you could make a mockup of the header with the button on the right side?

For the dark theme, I incorrectly assumed that I was editing a css file that affected both themes. The changes in this PR should be able to be directly copied to the other theme, as I made zero color related changes.

**Comment by PuttItOut** [comment]
Breaking Layout:
http://imgur.com/d42jsrt
http://imgur.com/fiJohiY

**Comment by voat** [comment]
Sweet. Thank you for reporting this. I guess I'll have to be more careful with future PRs. I'll revert this one for now.

**Comment by PuttItOut** [comment]
At this time, I think Nurdoidz should approve any CSS/UI stuff. He has my full confidence at this stage.

On the CSS, yes, it can be structured better (which is why we have breaking changes). We have two main themes, default and dark, both of which are full themes in and of themselves so changes right now have to be duplicated in both places.

**Comment by voat** [comment]
I agree. In fact, I wouldn't mind having 2 people check any larger UI changes as things have gotten so big now that one person can not possible test everything in a timely manner.

**Comment by quantumwannabe** [comment]
Please see #299

**Pull request merged**
