### PR TITLE
We love our users!

### PR DESCRIPTION
**Pull request by thunderrabbit**
The only ones trying to hurt Voat will never read the message anyway, so let’s keep it positive!

### CODE REVIEW

**Comment by thunderrabbit** [comment]
I feel a little sad inside each time I read "Are you trying to hurt us?"   I propose changing it to a positive message because anyone who actually reads the message is by definition a good user!

**Comment by fringenerd** [comment]
Hm, not sure that's the best message. What about we canvas suggestions on /v/ideasforoat and hold a vote for the top 5/10 suggestions?

**Comment by thunderrabbit** [comment]
Good idea!    Before making the pull request, I tried to post the idea on /v/Feedback, but got blocked by Cloudflare because of the keywords "hurt voat" I guess.

**Comment by PuttItOut** [comment]
You guys are funny

**Comment by AlphaT3ch** [comment]
Heh, I first thought it looked scary too. I vote :+1: to merge it :D

**Pull request merged**
