### PR TITLE
Fix header positioning

### PR DESCRIPTION
**Pull request by Nurdoidz**
This should realign everything swimingly:

### CODE REVIEW

**Comment by voat** [comment]
Thank you for the fix. I can't describe how happy it makes me :dancer:

**Comment by voat** [comment]
Weird. I tested this locally and it looks like this:


untitled

**Comment by Nurdoidz** [comment]
Hm... I'll look into it right away. Wish everything would work without putting them in containers.

**Comment by voat** [comment]
I'm using firefox 35.0.1 but I just tested it and it looks the same in chrome.

**Comment by Nurdoidz** [comment]
Well at least it's now consistent across browsers, haha.

**Comment by voat** [comment]
awesome :dancer:

**Comment by voat** [comment]
It all started with the change of the logo btw.

**Comment by Nurdoidz** [comment]
I found the problem! Just didn't test it right. I will do a commit within the next few minutes.

**Comment by voat** [comment]
Awesome. No rush!

**Comment by Nurdoidz** [comment]
Atko. We have a billion users flooding in. It needs to be perfect! :-)

**Comment by voat** [comment]
Awwwww

**Pull request merged**
