### PR TITLE
"smarter" code wrap for markdown toolbar, preview for comment edits and source label for received PMs

### PR DESCRIPTION
**Pull request by DanielFlamino**
Nice title, isn't it? Moving on...

* Updated Web.config to use voat-logo.png instead of voat_je_suis_charlie.png (Previously seen in #442, which was closed for being so insignificant)

* PuttItOut bullied me into changing the "smart" code wrap to a "smarter" code wrap. ([Video](https://www.youtube.com/watch?v=_rmWmBNDDuY) (back to YouTube because pomf is gone, hurray for longer processing times! :/))

* Added preview to the edit comment form
image

* Added source label to received private messages
image

* And two commits (plus the other two that revert them) just to fill the commit history with trash! :D

EDIT:

* [Fixes image expandos not working on the preview for editing submissions.](https://voat.co/v/voatdev/comments/144188/343966)

### CODE REVIEW

**Comment by pharno** [comment]
just FYI, your title is a sign of too much in one pull request. IMHO each of the 3 points you mentioned should be its own pull request. makes it way easier to accept only parts of it.

**Comment by DanielFlamino** [comment]
Good point, I'll keep that in mind for future PRs.

**Comment by PuttItOut** [comment]
:)

**Comment by voat** [comment]
Thanks!

**Pull request merged**
