### PR TITLE
Added Toggle Night Mode Switch

### PR DESCRIPTION
**Pull request by quantumwannabe**
Added a toggle night mode switch like in this post: https://voat.co/v/ideasforvoat/comments/68347

Light Mode
Dark Mode

I didn't make the sprites, [@razuliserm](https://voat.co/user/razuliserm) did.

Did I put the handling request logic in the right place? I put it in AccountController as that was where user prefs are being set. Also, I have it create a new user prefs entry if the user doesn't have one (like in UserPreferences()). I'm not sure if this is necessary.

Let me know if this is a terrible idea to add, or if you have any feedback.

### CODE REVIEW

**Comment by voat** [comment]
Thank you for this PR. 

I am unable to merge this because the sprite author is unknown and there is no licensing information. In order to merge this, I would need to get a signed copyright transfer agreement from the author, or, a legally valid proof that the sprite can be used on voat with no restrictions. I suggest you replace the sprite with an icon from http://ionicons.com/ which we already use or http://www.famfamfam.com/lab/icons/silk/.

**Comment by quantumwannabe** [comment]
How about ion-ios-lightbulb and ion-ios-lightbulb-outline?

**Comment by quantumwannabe** [comment]
Added ionicons to spritesheet:
Light
Dark

**Comment by voat** [comment]
Look good. I see there is a missing route for the new endpoint. I'll add it and push this live if everything works out okay.

**Pull request merged**
