### PR TITLE
adds getDomainName

### PR DESCRIPTION
**Pull request by moshmage**
IT appears there's some spacing issue, but it was fine when I first wrote it; I'm guessing it's a glitch?

### CODE REVIEW

**Comment by deltaidea** [comment]
Still don't know how this function is ought to be used. There're no mentions of it in the project. Maybe we can remove it completely, because [you ain't gonna need it](https://en.wikipedia.org/wiki/You_aren't_gonna_need_it).

**Comment by moshmage** [comment]
@deltaidea I kindly agree with the YAGNI idea, but the `return "notdone.com"` made me shiver so I just took action :P

**Comment by quantumwannabe** [comment]
I'm not sure that that javascript function is used. The domains that appear next to a submission (e.g. youtube.com appearing next to a YouTube link) are extracted by [GetDomainFromUri](https://github.com/voat/voat/blob/cad35c1647e651c572c791353f44364288f482dc/Whoaverse/Whoaverse/Utils/UrlUtility.cs#L28-40), which is a server-side function.

**Comment by PuttItOut** [comment]
Closing because of conflicts. Appreciate your time and help.

**Pull request closed without merging**
