### PR TITLE
More contrast, wider container, mobile sidebar functions, new spritesheet, favicon

### PR DESCRIPTION
**Pull request by Nurdoidz**
*Whew!* This one took several days, mostly due to testing 'n tweaking and that wretched spritesheet. Let's see how long I spend just going over the changes.

#### Code blocks will now get a scroll bar instead of wrapping long lines.

| Preview |
| --- |
|  |
| *Instead of wrapping the long line, the code block will add a scrollbar so code is easier to read.* |

Code blocks that have lines short enough not to wrap will remain without a scrollbar.

#### 'My subverses' list now has an arrow next to it to better distinguish itself as a drop-list.

| Preview |
| --- |
|  |
| *Isn't it cute?* |

Night mode has its own variation, as well!

#### Child comments are given alternating background colors.

| Preview |
| --- |
|  |
| *With more comments being the norm now, this'll make it easier to follow threads.* |

#### 'Subscribe', 'sub name', 'search', 'subscriber count' sidebar functions are now visible on mobile view.

| Preview |
| --- |
|  |
| *'Search', 'sub name', 'subscribe', and 'subscriber count' now sit at the top!* |

#### New favicon.ico

To match the new logo!

#### More general contrast.

| Preview |
| --- |
|  |
| *Everything isn't so washed-out now.* |

#### Most buttons are now consistent in their look.

Other buttons will now follow the jelly-like buttons on the front page.

#### Front page layout changed to table-based HTML instead of CSS.

Complete with 3D borders, GIFs, JPGs, full-width text, Times New Roman, patterned-backgrounds, and Comic Sans.

#### Container width is increased to 1200px (was 1075px).

More content without too much whitespace!

#### Child comments are less indented to fit more text.

This, combined with the container widening, will decrease scrolling and keep the user focused on the discussion.

#### Spritesheet changed to majority vector graphics and somewhat more contrast.

This should make some of the icons look less pixel-y. It also allows me to change the size of the icons without having to redraw everything.

#### Removed a trailing space.

No one likes trailing spaces. Especially that sneaky one.

### CODE REVIEW

**Comment by voat** [comment]
Wow, these are some well needed changes! It must have taken at least a week to put together! I will merge it now and do a few local tests. If all goes well, I'll comment here again and let you know when it goes love. Thank you for all the effort you've put so far into making voat a better place!

**Comment by DanielFlamino** [comment]
[Screw it, I'll use them in GitHub as well...](https://i.imgur.com/IpCWys0.gif) That's some damn fine work you did here.


>Front page layout changed to table-based HTML instead of CSS.

>Complete with 3D borders, GIFs, JPGs, full-width text, Times New Roman, patterned-backgrounds, and Comic Sans.

You had me there for a bit. [MRW](https://i.imgur.com/qip27DV.gif)

**Comment by Nurdoidz** [comment]
@voat 

> If all goes well, I'll comment here again and let you know when it goes **love.**

Confirmed. Voat *is* love.

@DanielFlamino 

Thanks! And huehuehue...

**Comment by voat** [comment]
Live. I meant live! :p

Alright, here are the results of my testing.

* There is now a scrollbar when viewing on mobile:

scroll bar

* On mobile, child comments are not given alternating background colors (I'm not sure if you intended this to remain unchanged):

child comments

Other than that, I couldn't find anything out of the ordinary.

**Comment by Nurdoidz** [comment]
> There is now a scrollbar when viewing on mobile

Interesting. I'll see what I can do.

> On mobile, child comments are not given alternating background colors (I'm not sure if you intended this to remain unchanged):

Ah, I see what happened. I only intended the borders to disappear. I'll get on it!

**Comment by DanielFlamino** [comment]
I was going to say that I can't see the favicon that well against the tab colour, but I guess that is because my Chrome theme is mostly bluish tones and as [you can see here](http://i.imgur.com/yzFqv3d.png) same thing sort of happens with Twitter, so really no need to worry I guess. Once again, great job!

**Comment by Nurdoidz** [comment]
I've darkened the outline anyway. It looked a little odd even on my Firefox theme.

**Pull request merged**
