### PR TITLE
Implement #201: Separate action buttons from sorting buttons

### PR DESCRIPTION
**Pull request by Nurdoidz**
I spent a few hours on this one just trying out different layouts, but this is the one I settled on. They stand out by their color. I wanted to separate the tab menu buttons from the others, but I found that it complicates the layout a lot due to how everything is positioned on the header bar. I hope this is sufficient.

### CODE REVIEW

**Comment by voat** [comment]
Wow that was fast! I think the color will do just fine, "physical" separation would definitely require a lot of fiddling in order to get it to play nice on mobile. :+1:

**Comment by voat** [comment]
I just pushed this live but I think something isn't working out - when you view the comments section header bar buttons and logo gets out of alignment.

**Comment by voat** [comment]
This only seems to be affecting firefox:

misalignment

**Comment by Nurdoidz** [comment]
Wowee, why hasn't this popped up in my tests?! I will fix it immediately.

**Pull request merged**
