### PR TITLE
Optimize Static Graphics

### PR DESCRIPTION
**Pull request by Saturate**
This shaves around 50% off the size of the static graphics.

### CODE REVIEW

**Comment by sergiotapia** [comment]
What was used to optimize the image? I used ImageOptim on my mac and got:

image

**Comment by Saturate** [comment]
I used the service https://kraken.io/
All my other projects does asset optimization in a deployment pipeline.

Not that I did it with all the pictures in the folder, that might do something as well.

**Comment by quantumwannabe** [comment]
Did you do lossy or lossless compression?

**Comment by Saturate** [comment]
Lossless :-)

**Comment by joshua-stone** [comment]
I've been able to get further savings by running optipng and advdef on my own hardware:

    optipng -i0 -o7 -zm1-9 -strip all -fix image.png
    advdef -z4 -i 1000 image.png

You can also save a few extra bytes by running the images through deflopt and defluff.

[Here's a comparison of tools that optimize PNG file size in different ways](http://css-ig.net/png-tools-overview.html)

**Comment by voat** [comment]
Thank you @Saturate, every little bit helps.

**Pull request merged**
