### PR TITLE
Appoint new admin on account deletion

### PR DESCRIPTION
**Pull request by Scaarus**
When an admin deletes their account select a new admin by getting the moderator with the highest power level. If multiple moderators have same level, get the oldest moderator.

### CODE REVIEW

**Comment by Aaron-P** [comment]
It might be a good idea to have some sort of activity check if it's possible, e.g. should it make someone an admin who hasn't logged in for 5 years or something.

**Comment by Scaarus** [comment]
What would be the best time frame for that? Also, should we check that the user has activity in the subverse or just general activity?

**Comment by Aaron-P** [comment]
I don't think subverse activity is really required for this case, it's more to try to prevent the role from going to an account that has been abandoned.  Even if it's a fairly lenient time span it's better than nothing.  Also it should send a notification to the person it has made an admin.

**Comment by Scaarus** [comment]
@Aaron-P Something along the lines of this? It checks if a mod has activity in the past 30 days before appointing. If no mod has activity, it just goes with the oldest. While there could be an inactive mod promoted, it should still allow for a subverse request.

**Comment by TNTGav** [comment]
How about simply looking at the LastLoginDateTime, which is currently in AspNetUsers?

That will give the truest indication of whether someone is active or not.

**Comment by PuttItOut** [comment]
Closing because of conflicts.

**Pull request closed without merging**
